version: '0.2'

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - wget --progress=dot:mega https://downloads.raspberrypi.org/raspbian_lite_latest
      - unzip raspbian_lite_latest
      - mkdir pi_image
      - mknod /dev/loop0 b 7 0
      - mount --verbose --options offset=272629760 2019-09-26-raspbian-buster-lite.img pi_image
      - |
          chroot pi_image /bin/sh << "EOF"
          apt-get update --assume-yes
          apt-get upgrade --assume-yes
          apt-get autoremove --assume-yes
          EOF
      - umount pi_image

artifacts:
  files:
    - "2019-09-26-raspbian-buster-lite.img"
